### ISSUE TITLE
Potential data-binding version conflict

### ISSUE THREAD

**Issue by thuutin** [skedgo/DateTimeRangePicker#10]
:DateTimeRangePicker2:compileDebugJavaWithJavac FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':DateTimeRangePicker2:compileDebugJavaWithJavac'.
> java.lang.annotation.IncompleteAnnotationException: android.databinding.BindingBuildInfo missing element enableDebugLogs

I get this error when building a project using `com.android.tools.build:gradle:2.3.0-beta1`, this library is using a different version `com.android.tools.build:gradle:2.2.3`.

**Comment by thuytrinh** [comment]
If you link to the library via JitPack, would it still throw that error?

**Comment by thuutin** [comment]
Yes. it will. we could instruct the user of this library to include 
```
ext.androidPluginVersion = '2.2.3'
ext.kotlinVersion = '1.0.5-3'
ext.supportLibraryVersion = '25.1.0'
```
to ensure the same version of databinding

**Comment by thuytrinh** [comment]
Have you tried `resolutionStrategy`? Would it work? For example, on top-level build file:
```groovy
allprojects {
  repositories {
    jcenter()
    maven { url "https://jitpack.io" }

  // A workaround for https://code.google.com/p/android/issues/detail?id=72430
  // and http://g.co/androidstudio/app-test-app-conflict.
  configurations.all {
    resolutionStrategy {
      force "com.android.support:design:$supportLibraryVersion"
      force "com.android.support:appcompat-v7:$supportLibraryVersion"
      force "com.android.support:support-v4:$supportLibraryVersion"
      force "com.android.support:support-annotations:$supportLibraryVersion"
    }
  }
}
```

**Comment by thuytrinh** [comment]
Close this because this seems to be app issue not library issue.
