### ISSUE TITLE
give gradle error 

### ISSUE THREAD

**Issue by rajam1215** [skedgo/DateTimeRangePicker#2]
Error:Failed to resolve: com.github.skedgo:activity-animations:v1.0

**Comment by rajam1215** [comment]
Error:Failed to resolve: com.github.skedgo:activity-animations:v1.0

**Comment by zakirhussain49** [comment]
Hi Rajam,

Put this

 sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

in your app gradle .


like this 



android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    dataBinding { enabled = true }
    defaultConfig {
        applicationId ""
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
}

**Comment by rajam1215** [comment]
hello sir

thanks i try this code

**Comment by rajam1215** [comment]
steel problem not solve again 
this error show
Error:Failed to resolve: com.github.skedgo:activity-animations:v1.0

please give me any soultion

**Comment by rajam1215** [comment]
now error is solve with this
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

and 
other code is

repositories {
    maven { url "https://jitpack.io" }
}
with this code run..


after solving this issue .the recent problem is 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.a1neclick.myapplication/skedgo.datetimerangepicker.DateTimeRangePickerActivity}: java.lang.IllegalStateException: intent.extras must not be null

              Caused by: java.lang.IllegalStateException: intent.extras must not be null
                                                         at skedgo.datetimerangepicker.DateTimeRangePickerActivity.onCreate(DateTimeRangePickerActivity.kt:47)

can u give any solution

**Comment by zakirhussain49** [comment]
put this 
repositories {
    jcenter()
    maven { url "https://jitpack.io" }
}

in app gradle 

problem will be solve

**Comment by thuytrinh** [comment]
Right, you'll need JitPack and [Kotlin setup](https://kotlinlang.org/docs/tutorials/kotlin-android.html) to successfully build the library project.

**Comment by rajam1215** [comment]
ok, let me heck it

i put this already jcenter()
maven { url "https://jitpack.io" }
}
          Caused by: java.lang.IllegalStateException: intent.extras must not be null
                                                     at skedgo.datetimerangepicker.DateTimeRangePickerActivity.onCreate(DateTimeRangePickerActivity.kt:47)

but give this error ,  i recheck from my end  then i notify u

**Comment by thuytrinh** [comment]
@rajam1215 To launch `DateTimeRangePickerActivity`, u gotta use some `newIntent()`s. See https://github.com/skedgo/DateTimeRangePicker#usage.
