### ISSUE TITLE
Getting intent.extra null pointer exception

### ISSUE THREAD

**Issue by zakirhussain49** [skedgo/DateTimeRangePicker#3]
Hi , 
I am creating a  new project in which i have pasted your .kt file and rec , but when I define DateTimeRangePickerActivity as a LAUNCHER Activity in mainfeast and try to build project i got an error .
java.lang.IllegalStateException: intent.extras must not be null.
please help , I have not too much idea on Kotlin

**Comment by thuytrinh** [comment]
@zakirhussain49 I've updated README to showcase the usage as well as how to launch the demo.
