### ISSUE TITLE
Intent Error

### ISSUE THREAD

**Issue by rajam1215** [skedgo/DateTimeRangePicker#6]
Caused by: java.lang.IllegalStateException: intent.extras must not be null
at skedgo.datetimerangepicker.DateTimeRangePickerActivity.onCreate(DateTimeRangePickerActivity.kt:47)

This Error come When we use Intent in MainActivity java class for go in DateTimeRangePickerActivity kotlin class

**Comment by thuytrinh** [comment]
You must use `newIntent()` to create intent to launch `DateTimeRangePickerActivity` like in https://github.com/skedgo/DateTimeRangePicker#usage.

**Comment by zakirhussain49** [comment]
Hi Rajam,

Put the below check in DateTimeRangePickerActivity

if (intent.extras != null)
      viewModel.handleArgs(intent.extras)

and after then put the below code in DateTimeRangePickerViewModel

  internal var timeZone: TimeZone? = TimeZone.getTimeZone(KEY_TIME_ZONE)

**Comment by rajam1215** [comment]
Ok, Very Thanks
